import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tourism App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Mbuga PhotoGraphy"
        message="Looking to document your Safari to the Kenyan wild? We got you"
      />
    </div>
  );
}
