import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Slider from "../components/Slider";
import { sliderData } from "../data/sliderData";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tourism App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Mbuga PhotoGraphy"
        message="Looking to document your Safari to the Kenyan wild? Look no further"
      />
      <Slider sliderData={sliderData} />
    </div>
  );
}
